# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana:5.5.1

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
RUN kibana-plugin install https://github.com/sivasamyk/logtrail/releases/download/v0.1.18/logtrail-5.5.1-0.1.18.zip